config/routes.rb
Ganli::Application.routes.draw do
  captcha_route
  get "/admin" ,to: "admin/admin#index"
  root "pages#index"

  resources :users,only:[:create,:edit,:update]
  resources :sessions, only: [:create, :destroy]
  resources :pages,only:[:show]
  resources :articles,only:[:index,:show] do  
  end
  resources :guest_messages,only:[:create,:new,:index]
  get "/classification/:id",to: "articles#classification",as: "classification"
 
  scope '/register' do
    get "/",to: "register#email_validate_from_user",as: "register"
    #get "/",to: "register#email",as: "register"
    #post "/email_validate",to: "register#email_validate"
    #get "/user_validate",to: "register#email_validate_from_user"
  end

  namespace 'admin' do
    root "admin#index"
    resources :articles do
      collection do
        get 'audit'
      end
      member do
        get 'audit_edit'
        patch 'audit_article'
      end
    end
    resources :classifications
    resources :navigations
    resources :pages
    resources :admin_menus,only: [:index,:new,:create]
    resources :permissions
    resources :groups
    resources :users do
      collection do
        get 'audit'
      end
      member do
        post 'audit_pass'
      end
    end
    resources :affair_form_instance_audit_logs,only:[:index,:new,:create]
    resources :affair_forms do
      collection do
        get 'apply'
        get 'propose'
      end
      resources :affair_form_instances
    end
    resources :affair_form_instances,only:[:show,:destroy] do
      collection do
        get 'list'
      end
      member do
        get 'admin_view'
      end
    end
    resources :documents do
      collection do
        get 'audit'
      end
      member do
        get 'audit_download'
        get 'download'
      end
    end
    resources :friendly_links
    resources :friendly_link_classifications
    resources :lunches
    resources :guest_messages
    resources :left_navs
    resources :messages do
      collection do
        get 'outbox'
        get 'new_message_notice'
        get 'download*path',action: :download,as: :download#,constraints: {path: /[^\/]*/}
        get 'crocodoc*uuid',action: :crocodoc,as: :crocodoc
      end
      member do
        get 'preview'
      end
    end
    
    resources :announcements do
      collection do
        get 'view_index'
      end
    end

    post 'files/imageup',to: 'files#imageup'
    post 'files/fileup',to: 'files#fileup'
    post 'files/imagemanger',to: 'files#imagemanger'
    get 'files/thumb/:imagename',to: 'files#thumb'

  end

  get '/bbs',to: 'bbs/topics#index'
  
  namespace 'bbs' do
    resources :replies,only:[:destroy] do
      member do
        post 'change_status'
      end
    end

    resources :topics do
      collection do
        get 'audit'
        get 'replies_audit'
      end
      member do
        get 'show_content'
        get 'show_reply_content'
        post 'change_status'
      end
      resources :replies do
        collection do
          get 'audit'
        end
        member do
          post 'change_status'
        end
      end
    end
  end

  get '/login',to:'sessions#new'
  get '/profile',to: 'users#profile',as: "profile"
  patch 'edit_profile',to: 'users#edit_profile'
  match '/logout',to:'sessions#destroy',via: :delete

  get '/page/service',to: 'pages#service'
  get '/search',to: 'articles#search',as: "search"
end

app/models/guest_message.rb
# == Schema Information
#
# Table name: guest_messages
#
#  id         :integer          not null, primary key
#  status     :integer          default(0)
#  nickname   :string(255)
#  content    :text
#  ip         :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class GuestMessage < ActiveRecord::Base
	validates :nickname,:content,presence: true

	scope :public,->{
		where(status: 1)
	}
end

app/controllers/admin/guest_messages_controller.rb
class Admin::GuestMessagesController < Admin::BaseController
	def index
		@audit_guest_messages = GuestMessage.where status:0#待审核
		@guest_messages = GuestMessage.where status:1#审核通过
	end

	def new
		@guest_message = GuestMessage.new
	end

	def create
		@guest_message = GuestMessage.new
		@guest_message.nickname = params[:guest_message][:nickname]
		@guest_message.content = params[:guest_message][:content]
		@guest_message.ip = request.remote_ip

		if @guest_message.valid?
			@guest_message.save
			flash_notice
			redirect_to action: :index
		else
			flash_error @guest_message
			redirect_to action: :new
		end
	end

	def edit
		@guest_message = GuestMessage.find params[:id]
		unless @guest_message.status.to_i == 0
			redirect_to action: :index
		end
	end

	def update
		@guest_message = GuestMessage.find params[:id]
		unless @guest_message.status.to_i == 0
			redirect_to action: :index
		end
		if params[:guest_message][:status].to_i == 0
			@guest_message.status = 1
		else
			@guest_message.status = 2
		end
		@guest_message.save
		flash[:notice] = "审核成功"
		redirect_to action: :index
	end

	def destroy
		@guest_message = GuestMessage.find params[:id]
		@guest_message.destroy

		redirect_to admin_guest_messages_path,flash: {notice: "删除成功"}
	end
end

app/controllers/guest_messages_controller.rb
class GuestMessagesController < ApplicationController
	def index
		@guest_messages = GuestMessage.public
	end

	def new
		@guest_message = GuestMessage.new
	end

	def create
		unless captcha_valid? params[:captcha]
			redirect_to new_guest_message_path,flash: {error: "验证码输入错误"} and return
		end
		@guest_message = GuestMessage.new
		@guest_message.nickname = params[:guest_message][:nickname]
		@guest_message.content = params[:guest_message][:content]

		if @guest_message.save
			redirect_to guest_messages_path,flash: {notice: "发布成功，等待管理员审核"}
		else
			redirect_to new_guest_message_path,flash: {error: @guest_message.errors.full_messages.join(",")}
		end
	end

end

app/helpers/admin/guest_messages_helper.rb
module Admin::GuestMessagesHelper
end

app/views/admin/guest_messages/_audit_list.html.haml
%tr
	%td
		=audit_guest_message.id
	%td
		=audit_guest_message.nickname
	%td
		=audit_guest_message.content
	%td
		=audit_guest_message.created_at.localtime.to_s(:db)
	%td
		=audit_guest_message.ip
	%td
		=link_to "<button class='tiny success button'>审核</button>".html_safe,edit_admin_guest_message_path(audit_guest_message)
		=button_to "删除",{action: "destroy",:id=>audit_guest_message},method: :delete,data:{confirm:"确定删除 #{audit_guest_message.nickname} 的留言?"},class: "button tiny alert"

app/views/admin/guest_messages/_guest_message.haml
%tr
	%td
		=guest_message.id
	%td
		=guest_message.nickname
	%td
		=guest_message.content
	%td
		=guest_message.created_at.localtime.to_s(:db)
	%td
		=guest_message.ip
	%td
		=button_to "删除",{action: "destroy",:id=>guest_message},method: :delete,data:{confirm:"确定删除 #{guest_message.nickname} 的留言?"},class: "alert tiny button"

app/views/admin/guest_messages/edit.html.haml
%table
	%tr
		%th
			ID
		%th
			昵称
		%th
			留言
		%th
			ip
	%tr
		%td
			=@guest_message.id
		%td
			=@guest_message.nickname
		%td
			=@guest_message.content
		%td
			=@guest_message.ip
=form_for [:admin,@guest_message] do |f|
	%p
		=f.label :status,"审核结果"
		=f.radio_button :status,"0"
		通过
		=f.radio_button :status,"1"
		拒绝
	%p
		=f.submit "提交审核结果",disable_with: '提交中...'

app/views/admin/guest_messages/index.html.haml
-content_for :actions_button do
	=link_to "添加留言",{action: :new},class: "tiny secondary button"
%p
	留言审核
-if @audit_guest_messages.empty?
	无需要审核的留言
-else
	%table
		%tr
			%td
				ID
			%td
				昵称
			%td
				留言
			%td
				发布时间
			%td
				ip
			%td
				操作
		=render partial: "audit_list",collection: @audit_guest_messages,as: :audit_guest_message
%p
	留言列表
%table
	%tr
		%td
			ID
		%td
			昵称
		%td
			留言
		%td
			发布时间
		%td
			ip
		%td
			操作
	=render partial: "guest_message",collection: @guest_messages

app/views/admin/guest_messages/new.html.haml
=form_for [:admin,@guest_message] do |f|
	%p
		=f.label :nickname,"昵称"
		=f.text_field :nickname
	%p
		=f.label :content,"您的留言"
		=f.text_area :content
	%p
		=f.submit "提交留言",disable_with: '提交中...'