config/routes.rb
Ganli::Application.routes.draw do
  captcha_route
  get "/admin" ,to: "admin/admin#index"
  root "pages#index"

  resources :users,only:[:create,:edit,:update]
  resources :sessions, only: [:create, :destroy]
  resources :pages,only:[:show]
  resources :articles,only:[:index,:show] do  
  end
  resources :guest_messages,only:[:create,:new,:index]
  get "/classification/:id",to: "articles#classification",as: "classification"
 
  scope '/register' do
    get "/",to: "register#email_validate_from_user",as: "register"
    #get "/",to: "register#email",as: "register"
    #post "/email_validate",to: "register#email_validate"
    #get "/user_validate",to: "register#email_validate_from_user"
  end

  namespace 'admin' do
    root "admin#index"
    resources :articles do
      collection do
        get 'audit'
      end
      member do
        get 'audit_edit'
        patch 'audit_article'
      end
    end
    resources :classifications
    resources :navigations
    resources :pages
    resources :admin_menus,only: [:index,:new,:create]
    resources :permissions
    resources :groups
    resources :users do
      collection do
        get 'audit'
      end
      member do
        post 'audit_pass'
      end
    end
    resources :affair_form_instance_audit_logs,only:[:index,:new,:create]
    resources :affair_forms do
      collection do
        get 'apply'
        get 'propose'
      end
      resources :affair_form_instances
    end
    resources :affair_form_instances,only:[:show,:destroy] do
      collection do
        get 'list'
      end
      member do
        get 'admin_view'
      end
    end
    resources :documents do
      collection do
        get 'audit'
      end
      member do
        get 'audit_download'
        get 'download'
      end
    end
    resources :friendly_links
    resources :friendly_link_classifications
    resources :lunches
    resources :guest_messages
    resources :left_navs
    resources :messages do
      collection do
        get 'outbox'
        get 'new_message_notice'
        get 'download*path',action: :download,as: :download#,constraints: {path: /[^\/]*/}
        get 'crocodoc*uuid',action: :crocodoc,as: :crocodoc
      end
      member do
        get 'preview'
      end
    end
    
    resources :announcements do
      collection do
        get 'view_index'
      end
    end

    post 'files/imageup',to: 'files#imageup'
    post 'files/fileup',to: 'files#fileup'
    post 'files/imagemanger',to: 'files#imagemanger'
    get 'files/thumb/:imagename',to: 'files#thumb'

  end

  get '/bbs',to: 'bbs/topics#index'
  
  namespace 'bbs' do
    resources :replies,only:[:destroy] do
      member do
        post 'change_status'
      end
    end

    resources :topics do
      collection do
        get 'audit'
        get 'replies_audit'
      end
      member do
        get 'show_content'
        get 'show_reply_content'
        post 'change_status'
      end
      resources :replies do
        collection do
          get 'audit'
        end
        member do
          post 'change_status'
        end
      end
    end
  end

  get '/login',to:'sessions#new'
  get '/profile',to: 'users#profile',as: "profile"
  patch 'edit_profile',to: 'users#edit_profile'
  match '/logout',to:'sessions#destroy',via: :delete

  get '/page/service',to: 'pages#service'
  get '/search',to: 'articles#search',as: "search"
end

app/models/affair_form_instance.rb
# == Schema Information
#
# Table name: affair_form_instances
#
#  id             :integer          not null, primary key
#  title          :string(255)
#  form           :text
#  affair_form_id :integer
#  created_at     :datetime
#  updated_at     :datetime
#  audit_process  :string(255)
#  status         :integer          default(0)
#  proposer       :integer
#

class AffairFormInstance < ActiveRecord::Base
	serialize :audit_process
	belongs_to :affair_form
	belongs_to :proposer,foreign_key:"proposer",class_name:"User"
	has_many :logs,foreign_key: "instance_id",class_name:"AffairFormInstanceAuditLog",dependent: :destroy
	before_save :form_to_hash
	
	default_scope{
		order("created_at desc")
	}
	scope :audit_by_user,->(user){
		where("audit_process like ? AND status = ?","%'#{user.id}'%",0).select{|instance|
			user.id.to_s == instance.audit_process[instance.logs.size]
		}
	}

	scope :get_waiting, ->{
		where("status = 0")
	}

	scope :get_pass, -> {
		where("status = 1")
	}

	scope :get_reject, -> {
		where("status = 2")
	}

	def is_pass?
		status !=0 and audit_process.size == logs.size
	end

	def pass_status
		if status == 0
			0 #等待审核
		else
			if audit_process.size == logs.size#所有人都审核了一遍
				if logs.last.status == 0
					1 #通过审核
				else
					2 #审核拒绝
				end
			else
				2 #审核拒绝
			end
		end
	end

	def last_approver
		if logs.size
			logs.last.approver.name
		end
	end

	def current_status_to_s
		case pass_status
		when 0
			"等待" + audit_user_name = User.find(audit_process[logs.size]).name + "审核"
		when 1
			"审核通过"
		when 2
			"审核拒绝"
		end
	end

	def audit_process_to_s
		audit_process.map.with_index{ |user,i| 
				c_user = User.find(user)
				"#{i+1}.#{c_user.name}(#{c_user.group.name})"
			}.join " -> "
	end

	def form_to_hash
		doc = Nokogiri::HTML(self.form)
		doc.css("td").each_with_index{|td,i| i.even? ? td['class'] = 'field' : td['class'] = 'value' }
		self.form = doc.serialize
	end

	def get_values
        doc = Nokogiri::HTML(self.form)
        doc.css(".value").map{|value| value.children.text.strip }
    end
end

app/controllers/admin/affair_form_instances_controller.rb
class Admin::AffairFormInstancesController < Admin::BaseController
	def index

	end

	def list

		if !!params[:start_date] and !!params[:end_date] #提交了按分类查看

			case params[:affair_form_audit_status]
			when '1' #审核通过
				status = 1
			when '2' #审核进行中
				status = 0
			when '3' #审核拒绝
				status = 2
			end

			begin
				@start_date = "#{params[:start_date][:year]}-#{params[:start_date][:month]}-#{params[:start_date][:day]}".to_date
				@end_date = "#{params[:end_date][:year]}-#{params[:end_date][:month]}-#{params[:end_date][:day]}".to_date
				if !!params[:affair_form_type] and params[:affair_form_type] != '0' #选择了表单类型
					@instance_tmp = AffairForm.find(params[:affair_form_type])
					if params[:affair_form_audit_status] == '0'
						@instances = AffairFormInstance.where(:affair_form_id => params[:affair_form_type], :created_at => @start_date..@end_date.tomorrow).paginate(:page=>params[:page],per_page: 30)
					else
						@instances = AffairFormInstance.where(:status => status,:affair_form_id => params[:affair_form_type], :created_at => @start_date..@end_date.tomorrow).paginate(:page=>params[:page],per_page: 30)
					end
				else#全部表单
					if params[:affair_form_audit_status] == '0'
						@instances = AffairFormInstance.where(:created_at => @start_date..@end_date.tomorrow).paginate(:page=>params[:page],per_page: 30)
					else
						@instances = AffairFormInstance.where(:status => status,:created_at => @start_date..@end_date.tomorrow).paginate(:page=>params[:page],per_page: 30)
					end
				end
			rescue
				flash[:error] = "时间格式不正确"
				redirect_to list_admin_affair_form_instances_path
				@instances = []
			end
		else
			@start_date = @end_date = Time.now
			@instances = AffairFormInstance.all.paginate(:page=>params[:page],per_page: 10)
		end

		@instances = @instances.to_a
		
		respond_to do |format|
    		format.html
    		format.xlsx{
    			if @instance_tmp.id == 3 #请假登记表
    				render "qingjiadengjibiao.xlsx.axlsx"
    			elsif @instance_tmp.id == 5 #公务出差表
    				render "gongwuchuchaibuchangqianshoubiao.xlsx.axlsx"
    			end
    		}
    		format.json{
    			render json: params
    		}
   		end
	end

	def admin_view
		@instance = AffairFormInstance.find params[:id]
		session[:return_to] = list_admin_affair_form_instances_path
	end

	def show
		@instance = AffairFormInstance.find params[:id]
		if @instance.proposer != current_user
			access_forbidden
		end
		session[:return_to] = propose_admin_affair_forms_path
	end

	def new
		@affair_form = AffairForm.find params[:affair_form_id]
		@affair_form_instance = AffairFormInstance.new
		@affair_form_instance.title = @affair_form.title
		@affair_form_instance.form = @affair_form.form
		@affair_form_instance.audit_process = @affair_form.audit_process
	end
	def create
		@affair_form = AffairForm.find params[:affair_form_id]
		@affair_form_instance = AffairFormInstance.new

		@affair_form_instance.title = @affair_form.title
		@affair_form_instance.affair_form = @affair_form
		@affair_form_instance.form = params[:affair_form_instance][:form]
		@affair_form_instance.audit_process = @affair_form.audit_process
		@affair_form_instance.proposer = current_user

		@affair_form_instance.save
		flash[:notice] = "申请成功 等待审核"
		redirect_to action: :apply,controller: :affair_forms
	end

	def destroy
		@instance = AffairFormInstance.find params[:id]
		if @instance.proposer != current_user
			access_forbidden
		end
		@instance.destroy

		redirect_to session[:return_to]
	end
end

app/helpers/admin/affair_form_instances_helper.rb
module Admin::AffairFormInstancesHelper
	def affair_form_types_radio(affairs,affair_form_type)
		if  affair_form_type == '0' or !affair_form_type
			html = content_tag(:input, nil, :type => "radio", :name => "affair_form_type", 
					:value => 0, :checked => "checked",:id => "affair_form_type_id_0")
		else
			html = content_tag(:input, nil, :type => "radio", :name => "affair_form_type", 
					:value => 0, :id => "affair_form_type_id_0")
		end
		
		html+=content_tag(:label, "全部", :for => "affair_form_type_id_0")
		affairs.each do |affair|
			if !!affair_form_type and affair_form_type.to_i == affair.id.to_i
				html+=content_tag(:input, nil, :type => "radio", :name => "affair_form_type", 
					:value => affair.id, :checked => "checked", :id => "affair_form_type_id_#{affair.id}")
			else
				html+=content_tag(:input, nil, :type => "radio", :name => "affair_form_type", 
					:value => affair.id, :id => "affair_form_type_id_#{affair.id}")
			end
			html+=content_tag(:label, affair.title, :for => "affair_form_type_id_#{affair.id}")
		end
		html.html_safe
	end

	def affair_form_audit_status_radio(audit_status)
		html = ""
		list = ["全部", "审核通过", "审核进行中", "审核拒绝"]
		list.each_with_index do |li,i|
			if audit_status.to_i == i
				html += content_tag(:input, nil, :type => "radio", :name => "affair_form_audit_status",
				:value => i,:checked => "checked",:id => "affair_form_audit_status_#{i}")
			else
				html += content_tag(:input, nil, :type => "radio", :name => "affair_form_audit_status",
				:value => i,:id => "affair_form_audit_status_#{i}")
			end
			html += content_tag(:label, li, :for => "affair_form_audit_status_#{i}")
		end

		return html.html_safe
	end
end

app/views/admin/affair_form_instances/admin_view.html.haml
-content_for :actions_button do
	=link_to "打印","#",onclick: "window.print();return false;",class: "tiny secondary button"
-if not @instance.is_pass?
	=render partial: "/admin/delete_button",locals: {name: "删除此次申请"}
.printable
	%h4
		=@instance.title
	%p
	="申请时间： #{@instance.created_at.localtime.to_s(:db)}"
	=@instance.form.html_safe
	%p="审核状态: " << @instance.current_status_to_s
	-unless @instance.logs.empty?
		%table
			%caption
				审核日志
			%tr
				%td 审核人
				%td 审核时间
				%td 审核结果
				%td 审核备注
			-@instance.logs.each do |log|
				%tr
					%td=User.find(log.approver).name
					%td=log.created_at.localtime.to_s(:db)
					%td=(log.status == 0) ? "通过" : "不通过"
					%td=log.remark

app/views/admin/affair_form_instances/list.html.haml
-if @instance_tmp and params[:affair_form_audit_status].to_i == 1 and @instances.any?
	-content_for :actions_button do
		=link_to "导出excel",request.fullpath.sub('?','.xlsx?'),class: "tiny secondary button"
按日期区间
=form_tag list_admin_affair_form_instances_path,class: "query_by_data",method: :get do
	%label 起始日期	
	=select_date @start_date,:prefix => "start_date",start_year: 2013
	%label 结束日期
	=select_date @end_date,:prefix => "end_date",start_year: 2013
	.type-select
		%label 表单类型
		=affair_form_types_radio(AffairForm.all, params[:affair_form_type])
	.audit-status-select
		%label 审核状态
		=affair_form_audit_status_radio(params[:affair_form_audit_status].to_i)
	=submit_tag "查看"
-if @instances.empty?
	没有申请表
-else
	%table
		%tr
			%td
				ID
			%td
				申请表标题
			%td
				申请时间
			%td
				申请人
			%td
				状态
		-@instances.each do |instance|
			%tr
				%td=instance.id
				%td=link_to instance.title,admin_view_admin_affair_form_instance_path(instance)
				%td=instance.created_at.localtime.to_s(:db)
				%td=instance.proposer.name
				%td
					=instance.current_status_to_s
					="(终审人#{instance.last_approver})" if instance.is_pass?
	=will_paginate @instances

app/views/admin/affair_form_instances/list.xls.erb
<table>
    <thead>
        <tr>
            <% @instance_tmp.get_fields.each do |th| %>
                <th><%= th %></th>
            <% end %>
        </tr>
    </thead>
    <tbody>
        <% @instances.each do |instance| %>
            <tr id="<%= instance.id %>">
                <% instance.get_values.each do |value| %>
                    <td><%= value %></td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/admin/affair_form_instances/new.html.haml
=render partial: 'admin/ueditor/no_toolbar',locals:{ueditor_id:"affair_form_instance_form"}
%p
	审核流程
	=@affair_form_instance.audit_process_to_s
=form_for [:admin,@affair_form,@affair_form_instance] do |f|
	%h4
		=@affair_form.title
	%p
		=@affair_form.describe
	%p
		=f.label :form,"申请表"
		=f.text_area :form
	%p
		=f.submit "提交申请",disable_with: '提交中...'

app/views/admin/affair_form_instances/show.html.haml
-if not @instance.is_pass?
	=render partial: "/admin/delete_button",locals: {name: "删除本次申请"}
%h4
	=@instance.title
=@instance.form.html_safe
%p="审核状态: " << @instance.current_status_to_s
-unless @instance.logs.empty?
	%table
		%caption
			审核日志
		%tr
			%td 审核人
			%td 审核时间
			%td 审核结果
			%td 审核备注
		-@instance.logs.each do |log|
			%tr
				%td=User.find(log.approver).name
				%td=log.created_at.to_date
				%td=(log.status == 0) ? "通过" : "不通过"
				%td=log.remark